<?php
/**
 * @var Klevu\Logger\Block\Adminhtml\Form\Button\LogDownloadButton $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$buttonLabel = $block->getDataUsingMethod('button_label');
$destinationUrl = $block->getDataUsingMethod('destination_url');
$htmlId = $block->getDataUsingMethod('html_id');
?>
<?php if ($buttonLabel && $destinationUrl): ?>
    <button id="<?php echo $block->escapeQuote($htmlId); ?>"
            class="scalable"
            type="button">
        <span><?php echo $block->escapeHtml(__($buttonLabel)); ?></span>
    </button>

    <?php
    $scriptString = <<<script

    require(["prototype"], function(){
        $("{$block->escapeQuote($htmlId)}").observe("click", function () {
            new Ajax.Request("{$block->escapeUrl($destinationUrl)}", {
                method: 'POST',
                onComplete: function(data) {
                    setLocation("{$block->escapeUrl($destinationUrl)}");
                }
            });
        });
    });

script;
    ?>
    <?= $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript'],
        $scriptString,
        false
    ) ?>
<?php endif; ?>
